### ISSUE TITLE
Class 'OCA\\groupoffice\\Group' not found at

### ISSUE THREAD

**Issue by githubrsys** [horfic/groupoffice-owncloud#3]
actual master release ends up in a 500 apache error due

```
{"app":"PHP","message":"Class 'OCA\\groupoffice\\Group' not found at \/var\/www\/web1\/html\/subdomains\/cloud\/owncloud\/apps\/groupoffice\/appinfo\/app.php#8","level":3,"time":"2014-10-04T11:29:08+00:00"}
```

Had to go back to commit cb27aa248a1e67dd355e2e129f1d73ca4b845e15
### environment
- OC -> 7.0.2 (stable)
- GO -> 5.0.81
- groupoffice-owncloud -> latest master from today*
### guess

group_groupoffice.php is not in namespaces

**Comment by horfic** [comment]
thanks, forgot to change it for github^^, fixed with current master
