### ISSUE TITLE
Cannot redeclare class OCA\\groupoffice\\Group

### ISSUE THREAD

**Issue by githubrsys** [horfic/groupoffice-owncloud#4]
{"app":"PHP","message":"Cannot redeclare class OCA\groupoffice\Group a
Cannot redeclare class OCA\groupoffice\Group at \/var\/www\/web1\/html\/subdomains\/cloud\/owncloud\/apps\/groupoffice\/lib\/groupofficestorage.php#0","level":3,"time":"2014-10-04T18:08:18+00:00"}
## guess

twice loaded?

**Comment by horfic** [comment]
their you go, was a mixup, i copied the group stuff into the storage file.
