### ISSUE TITLE
Undefined index: \\OC\\Files\\Storage\\Groupoffice

### ISSUE THREAD

**Issue by githubrsys** [horfic/groupoffice-owncloud#5]
{"app":"PHP","message":"Undefined index: \OC\Files\Storage\Groupoffice at \/var\/www\/web1\/html\/subdomains\/cloud\/owncloud\/apps\/files_external\/lib\/config.php#182","level":3,"time":"2014-10-04T18:16:18+00:00"}
## guess

It's getting funny

**Comment by highupsky** [comment]
I had the same problem for me it was a missing '/' at the begining of the absolute path to the owncloud.
